# Generated by Django 4.1.7 on 2024-04-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('jefe_auditoria', 'Jefe de Auditoria'), ('supervisor', 'Supervisor'), ('auditor', 'Auditor')], default='auditor', max_length=20),
        ),
    ]
